// Automatically generated by MockGen. DO NOT EDIT!
// Source: peermgmt.go

package mock_p2p

import (
	gomock "github.com/golang/mock/gomock"
)

// Mocknetwork_iface is a mock of network_iface interface
type Mocknetwork_iface struct {
	ctrl     *gomock.Controller
	recorder *Mocknetwork_ifaceMockRecorder
}

// Mocknetwork_ifaceMockRecorder is the mock recorder for Mocknetwork_iface
type Mocknetwork_ifaceMockRecorder struct {
	mock *Mocknetwork_iface
}

// NewMocknetwork_iface creates a new mock instance
func NewMocknetwork_iface(ctrl *gomock.Controller) *Mocknetwork_iface {
	mock := &Mocknetwork_iface{ctrl: ctrl}
	mock.recorder = &Mocknetwork_ifaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *Mocknetwork_iface) EXPECT() *Mocknetwork_ifaceMockRecorder {
	return _m.recorder
}

// NeighborReq mocks base method
func (_m *Mocknetwork_iface) NeighborReq() ([]string, error) {
	ret := _m.ctrl.Call(_m, "NeighborReq")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeighborReq indicates an expected call of NeighborReq
func (_mr *Mocknetwork_ifaceMockRecorder) NeighborReq() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NeighborReq")
}
